### PR TITLE
Update Sharethrough endpoint

### PR DESCRIPTION
**Pull request by madma**
Story: [#166961230](https://www.pivotaltracker.com/story/show/166961230)

Dependency: sharethrough/sfp-ad-server#18

### CODE REVIEW

**Review by javadreamer — CHANGES_REQUESTED** [review]
Please add reference to the related story in the description.   

Please add tasks to the story so that faux and dumb-waiter respond to both the header-bid endpoint and the new one.  Inspector AdGet has a dependency, with force prebid, for there to be the corresponding endpoint on dumb-waiter.

**Comment by madma** [comment]
> Please add reference to the related story in the description.
> 
> Please add tasks to the story so that faux and dumb-waiter respond to both the header-bid endpoint and the new one. Inspector AdGet has a dependency, with force prebid, for there to be the corresponding endpoint on dumb-waiter.

Tasks added to Pivotal story.

**Review by epechuzal — APPROVED** [review]

**Review by maphe — APPROVED** [review]
Changes are good but there is a change that needs to go on SFP ad server first

**Review by javadreamer — APPROVED** [review]

**Comment by madma** [comment]
> Changes are good but there is a change that needs to go on SFP ad server first

@maphe just wanted to confirm that this PR can be unblocked now. The relevant PR for SFP Ad Server was merged yesterday: https://github.com/sharethrough/sfp-ad-server/pull/18.

**Comment by madma** [comment]
> > Changes are good but there is a change that needs to go on SFP ad server first
> 
> @maphe just wanted to confirm that this PR can be unblocked now. The relevant PR for SFP Ad Server was merged yesterday: [sharethrough/sfp-ad-server#18](https://github.com/sharethrough/sfp-ad-server/pull/18).

Just noting for the record that the blocker by SFP Ad Server update has been cleared. Confirmed with @maphe.

**Pull request merged**
